### ISSUE TITLE
Dedicated server immediately crashes without any other mods.

### ISSUE THREAD

**Issue by Sonic2423** [RubixDev/Inventorio#338] opened 2024-04-05 03:07 UTC
Inventorio 1.10.2 introduced a bug which leads to the dedicated server not starting.

minecraft 1.20.4
neoForge 20.4.218
inventorio 1.10.2
kotlin 4.10
cloth config 13.0.121 (same error with or without this mod)

no other mods.
inventorio 1.10.1 works fine.

client runs fine with inventorio 1.10.2.

"Mixin prepare for mod inventorio failed preparing curios.CuriosClientPayloadHandlerMixin in inventorio-neoforge.mixins.json: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException java.lang.NullPointerException: Cannot invoke "net.neoforged.fml.ModList.getModFileById(String)" because the return value of "net.neoforged.fml.ModList.get()" is null"

Somewhat related:

inventorio 1.10.1 also crashes if curios-neoforge-7.3.4+1.20.4 is present on the dedicated server.

**Comment by RubixDev** [comment] 2024-04-05 05:11
Duplicate of #333. While waiting for the v1.10.3 release you can either downgrade to 1.10.1 or use the latest development build artifacts from [here](https://github.com/RubixDev/Inventorio/actions/runs/8549861624).
As for the crash with 1.10.1, I just opened #339.

**Closed by RubixDev** 2024-04-05 05:11 UTC
