### ISSUE TITLE
Request 1.20.1+: Allow a config to remove the Utility Belt or/and the Inventorio screen.

### ISSUE THREAD

**Issue by FernoXL** [RubixDev/Inventorio#319] opened 2024-03-19 00:59 UTC
I Like this mod and all its features but in most cases, I find myself using it mostly for the Swapped hand features as I think those do a better job at hotbar management than vanilla. An option to remove the additional Utility Belt slots or the Inventorio screen accompanying it would be great.
(This Would also probably allow us to use the default off-hand slots)
Thanks.

**Comment by FernoXL** [comment] 2024-03-19 01:03
Similar to Issue/ Suggestion https://github.com/RubixDev/Inventorio/issues/281 but with more detail.

**Comment by RubixDev** [comment] 2024-03-19 12:18
I'm sorry, what more are you suggesting than an option to disable the utility belt?

**Comment by FernoXL** [comment] 2024-03-23 11:32
You're right, I guess what I said wasn't adding more it was just slightly re-phrasing the request.
I was just hoping that when we disable both the Tool belt and the Utility Belt the Inventorio screen that they are attached to goes away as well.

I guess I could also ask, Why is there an Inventorio screen, was it not possible to add the related slots to the normal inventory screen?

**Comment by RubixDev** [comment] 2024-03-25 08:37
> I guess I could also ask, Why is there an Inventorio screen, was it not possible to add the related slots to the normal inventory screen?

Integrating all the Inventorio stuff into the vanilla screen would be very brittle and would easily break both with future minecraft versions and with other mods.

> I was just hoping that when we disable both the Tool belt and the Utility Belt the Inventorio screen that they are attached to goes away as well.

I guess I can make it so that screen is disabled when the utility belt, tool belt, and deep pockets are all disabled. But I'll still close this issue as a duplicate of #281

**Closed by RubixDev** 2024-03-25 08:37 UTC
Labels: duplicate, enhancement
