### ISSUE TITLE
when on a server, cant use inventorio inventory

### ISSUE THREAD

**Issue by dotMoontoon** [RubixDev/Inventorio#343] opened 2024-04-12 00:15 UTC
When using the inventorio inventory on a server, I cannot move items in the inventory, as they move back to where they were before, unless I shift click
I own the server and everything works fine in singleplayer

Video attached incase I phrased it poorly (sorry about weird aspect ratio)

https://github.com/RubixDev/Inventorio/assets/166770243/14d37117-a3ec-402d-99ed-2e4ce8848fc4

**Comment by RubixDev** [comment] 2024-04-23 07:40
I see you are using Minecraft 1.19.2. I no longer support that version and I can't reproduce that issue with 1.20.4. So I'll close this, but feel free to re-open it if you encounter the same issue in any 1.20 version.

**Closed by RubixDev** 2024-04-23 07:40 UTC
