### ISSUE TITLE
Stack limit with deep pockets

### ISSUE THREAD

**Issue by Uentpreseu** [RubixDev/Inventorio#217] opened 2023-02-02 15:21 UTC
First of all I love this mode dude keep going, soo I was playing with the mod and found out you can get stacks of 64 on items you shouldn't be allowed, like ender pearls, eggs and other items that only stack to certain limit this while using the deep pockets enchant, to replicate use leggings with the enchant, then fill your inventory whit anything (dirt f.e) including the extra inventory, empty a slot on the extra inventory and start picking up the item that you want to stack up to 64 (eggs, ender pearls, just stackable items to a limit) from the floor.

**Comment by RubixDev** [comment] 2024-03-27 07:00
Duplicate of #190

**Closed by RubixDev** 2024-03-27 07:00 UTC
Labels: duplicate
