### ISSUE TITLE
Sword items isn't working on the toolbar's sword slot.

### ISSUE THREAD

**Issue by SireAwfulThe1st** [RubixDev/Inventorio#330] opened 2024-03-30 20:17 UTC
https://github.com/RubixDev/Inventorio/assets/106896635/3246cad0-9b95-4646-805b-989f91bf40b6

Sword items randomly stopped working in the sword slot of the toolbar, not sure if it's a sudden bug or an underlying mod causes this

**Comment by RubixDev** [comment] 2024-03-30 23:51
Try disabling Jade for now. I'll try to fix this asap.

**Comment by RubixDev** [comment] 2024-03-31 01:31
nvm, this might not be Jade. I'll have to try around myself to see what causes this. In the meantime could you send me your mod list?

**Comment by RubixDev** [comment] 2024-03-31 06:32
Yea, this isn't Jade this time. I'll need a list of mods before I can find the issue. It doesn't seem to happen standalone.

**Comment by SireAwfulThe1st** [comment] 2024-04-01 17:56
> nvm, this might not be Jade. I'll have to try around myself to see what causes this. In the meantime could you send me your mod list?

Hello! I'm really sorry for the late reply, almost forgot that I had this issue open, with that said, sure my modlist will be in this modrinth pack if you don't mind.

https://drive.google.com/file/d/1jgMB_gQgPmjATcdPkTZw05d76ruM7Mg0/view?usp=sharing

**Comment by RubixDev** [comment] 2024-04-02 10:50
The issue seems to be with ChainMailed. I was able to reproduce this in a minimal setup using only ChainMailed and Inventorio (plus dependencies).

**Comment by RubixDev** [comment] 2024-04-02 10:55
Well duh, they [completely redefine the player's attack method](https://github.com/AstianBK/ChainMailed/blob/9b44c15d93371ad2a202a7ce24c4b36663025f06/src/main/java/com/TBK/chainmailed/common/mixins/PlayerMixin.java#L46-L209) instead of only tweaking it slightly, and they don't even use an `@Overwrite` which would cause a crash indicating that the two mods are incompatible. This will have to be fixed on their end, that code is just bad in its current state and there's not much Inventorio can do about that.

**Closed by RubixDev** 2024-04-02 10:55 UTC
Labels: incompatibilty, priority: high
