### ISSUE TITLE
Items picked up will create new stack in inventory when utility slot already has a non-full stack made.

### ISSUE THREAD

**Issue by Sugar-Pink** [RubixDev/Inventorio#265] opened 2023-08-30 01:21 UTC
Basically if I have torches x32 in my utility hand and I place one, then break it, it will not return to my utility hand and instead create a new stack in my inventory and I have to manually place it back in my utility stack.

**Comment by lucascoelho07** [comment] 2024-03-22 18:17
Duplicate of #305 ?

**Comment by RubixDev** [comment] 2024-03-27 06:55
> Duplicate of https://github.com/RubixDev/Inventorio/issues/305 (already fixed)?

indeed.

This bug was introduced in the 1.20 port and was fixed again in v1.10.0

**Closed by RubixDev** 2024-03-27 06:55 UTC
Labels: enhancement
