### ISSUE TITLE
Trinket Integration Seems To Break Serverside

### ISSUE THREAD

**Issue by BlueSquido** [RubixDev/Inventorio#344] opened 2024-04-14 00:00 UTC
Hosting a world locally through single player seems to work fine with the current trinkets implementation, but once I try it server sided on my dedicated server, the server crashes upon someone trying to join. I only have Trinkets, The Fabric API, Inventorio and its dependencies on the server. Turning off the trinkets support setting in the Inventorio config fixes the issue, but turning it back on crashes the server again. 
Heres the crash report given.
[crash-2024-04-13_23.07.49-server.txt](https://github.com/RubixDev/Inventorio/files/14968968/crash-2024-04-13_23.07.49-server.txt)

**Comment by RubixDev** [comment] 2024-04-14 01:26
Duplicate of #329. It's already fixed, I just need to finally publish another release. In the meantime you can use the latest development [build artifacts](https://github.com/RubixDev/Inventorio/actions/runs/8586866759)

**Closed by RubixDev** 2024-04-14 01:26 UTC
