### ISSUE TITLE
[Question] Extra slots not showing in Creative mode? (Fabric 1.20.4)

### ISSUE THREAD

**Issue by Gamemassa** [RubixDev/Inventorio#321] opened 2024-03-23 11:49 UTC
Hi, just curious, are the Utility Belt and Deep Pockets slots supposed to show up in Creative mode? Because if so, then that needs to be fixed because they're not showing up.

**Comment by RubixDev** [comment] 2024-03-27 01:47
Duplicate of #244

**Closed by RubixDev** 2024-03-27 01:47 UTC
Labels: duplicate
