### ISSUE TITLE
Cursor position is reset to centre of screen when clicking on inventory screen toggle button

### ISSUE THREAD

**Issue by Abbie5** [RubixDev/Inventorio#313] opened 2024-03-09 12:06 UTC
Personally, I find this jarring and would prefer if the cursor was moved to the new position of the button, or not moved at all.

**Comment by RubixDev** [comment] 2024-03-31 09:13
duplicate of #267 and fixed in v1.10.1

**Closed by RubixDev** 2024-03-31 09:13 UTC
Labels: enhancement
